#!/bin/bash
# =====================================================================
# MCPanel (mcpanel) - One-click Deployment Script
# Supported OS: Ubuntu / Debian (apt-based)
#
# Usage:
#   sudo bash preinstall.sh                     # deploy for the user who invoked sudo
#   sudo bash preinstall.sh mcserver            # specify the run user
#   MC_DIR=/path/to/mc sudo bash preinstall.sh  # set MC server directory (auto-detect + confirm by default)
#   MCRCON_PASS=xxx sudo bash preinstall.sh     # set RCON password (otherwise interactive)
#   MC_SERVICE_NAME=mc sudo bash preinstall.sh  # set MC service/screen/tmux session name (auto-detect default)
#   MC_LAUNCH_TYPE=systemd sudo bash preinstall.sh  # set manage type systemd/screen/tmux (auto-detect default)
#   PANEL_PROTO=http sudo bash preinstall.sh  # HTTP mode (INSECURE, HTTPS strongly recommended; default https)
#   MC_LAUNCH_CMD='bash start.sh' sudo bash preinstall.sh  # launch command for screen/tmux (auto default)
#   USE_VENV=n sudo bash preinstall.sh  # skip Python virtual environment (venv is the default)
#
# What it deploys:
#   1. System deps (python3/pip/build tools/Xvfb/x11vnc)
#   2. Python deps (requirements.txt, installed with --user for the run user)
#   3. Directory layout + HTTPS self-signed certificate
#   4. frp reverse proxy prompt (none / PROXY v1 / PROXY v2)
#   5. MC server directory detection (auto-detect + confirm; pre-set with MC_DIR)
#   6. Backup dir prompt (custom dir gets two subdirs; empty auto-creates default backup dir + two subdirs)
#   7. MC manage-type detection + env injection (SECRET_KEY/MCRCON_PASS/MC_DIR etc., merged into the main unit)
#   8. Passwordless sudo (systemctl MC / chattr / reboot)
#   9. systemd service (mcpanel.service) + gunicorn config (generated by frp mode)
# =====================================================================

set -e

RUN_USER="${1:-$SUDO_USER}"
RUN_USER="${RUN_USER:-$(whoami)}"

# ---------- CPU affinity (panel pinned to the last two cores, MC uses the front cores) ----------
# Auto-computed from core count; override with PANEL_CPU_AFFINITY
CPU_AFFINITY="${PANEL_CPU_AFFINITY:-}"
if [ -z "$CPU_AFFINITY" ]; then
    NCORES_TOTAL="$(nproc 2>/dev/null || echo 1)"
    if [ "$NCORES_TOTAL" -ge 2 ]; then
        CPU_AFFINITY="$((NCORES_TOTAL-2)) $((NCORES_TOTAL-1))"
    else
        CPU_AFFINITY="0"
    fi
fi
echo "  [INFO] CPU cores: ${NCORES_TOTAL:-$(nproc)}, panel affinity: ${CPU_AFFINITY} (override with PANEL_CPU_AFFINITY)"

# ---------- MC manage-type detection (systemd / screen / tmux) ----------
detect_mc_manage_type() {
    local svc sname tname
    svc="$(systemctl list-unit-files --type=service 2>/dev/null | awk '{print $1}' | grep -iE '^(minecraft|paper|spigot|purpur|bukkit|mc)\.service$' | head -1 | sed 's/\.service//')"
    if [ -n "$svc" ]; then
        echo "systemd $svc"; return
    fi
    sname="$(screen -ls 2>/dev/null | grep -oE '[0-9]+\.[A-Za-z0-9_.-]+' | head -1 | sed 's/^[0-9]*\.//')"
    if [ -n "$sname" ]; then
        echo "screen $sname"; return
    fi
    tname="$(tmux ls 2>/dev/null | awk -F: '{print $1}' | head -1)"
    if [ -n "$tname" ]; then
        echo "tmux $tname"; return
    fi
    echo "none none"
}

# Auto-detect MC manage type, ask for confirmation; if rejected, fill in manually
MC_LAUNCH_TYPE="${MC_LAUNCH_TYPE:-}"
if [ -z "${MC_SERVICE_NAME:-}" ] || [ -z "$MC_LAUNCH_TYPE" ]; then
    DETECTED="$(detect_mc_manage_type)"
    DETECT_TYPE="${DETECTED%% *}"; DETECT_NAME="${DETECTED#* }"
    if [ "$DETECT_TYPE" = "none" ]; then
        echo "  No MC manage type detected, please fill in manually:"
        read -r -p "  Manage type (systemd / screen / tmux, default systemd): " MC_LAUNCH_TYPE
        MC_LAUNCH_TYPE="${MC_LAUNCH_TYPE:-systemd}"
        read -r -p "  Service name / screen session / tmux session (default minecraft): " MC_SERVICE_NAME
        MC_SERVICE_NAME="${MC_SERVICE_NAME:-minecraft}"
    else
        echo "  Detected MC manage type: [${DETECT_TYPE}]   name: [${DETECT_NAME}]"
        read -r -p "  Use this result? (Y/n): " CONFIRM_MC
        if [[ "$CONFIRM_MC" =~ ^[Nn]$ ]]; then
            echo "  Fill in manually (overrides detection):"
            read -r -p "  Manage type (systemd / screen / tmux, default ${DETECT_TYPE}): " MC_LAUNCH_TYPE
            MC_LAUNCH_TYPE="${MC_LAUNCH_TYPE:-$DETECT_TYPE}"
            read -r -p "  Service / session name (default ${DETECT_NAME}): " MC_SERVICE_NAME
            MC_SERVICE_NAME="${MC_SERVICE_NAME:-$DETECT_NAME}"
        else
            MC_LAUNCH_TYPE="$DETECT_TYPE"; MC_SERVICE_NAME="$DETECT_NAME"
        fi
    fi
fi
# screen/tmux: launch command (defaults to start.sh under MC_DIR, else the first jar)
MC_LAUNCH_CMD="${MC_LAUNCH_CMD:-}"
if [ "$MC_LAUNCH_TYPE" != "systemd" ] && [ -z "$MC_LAUNCH_CMD" ]; then
    echo "  [${MC_LAUNCH_TYPE}] MC launch command (empty = auto use start.sh or first jar under MC_DIR):"
    read -r -p "  > " MC_LAUNCH_CMD
fi

if [ "$EUID" -ne 0 ]; then
  echo "Error: run with sudo: sudo bash preinstall.sh [run-user]"
  exit 1
fi
if ! id "$RUN_USER" >/dev/null 2>&1; then
  echo "Error: user $RUN_USER does not exist. Create it first: useradd -m -s /bin/bash $RUN_USER"
  exit 1
fi

# ---------- MC server directory detection (auto-detect + confirm; pre-set with MC_DIR) ----------
detect_mc_dir() {
    local pid dir rh
    # Priority: cwd of a running MC java process (paper/spigot/purpur/bukkit/fabric/forge etc.)
    pid="$(pgrep -f '\.jar.*(nogui|server|spigot|paper|purpur|fabric|forge)' 2>/dev/null | head -1 || true)"
    if [ -n "$pid" ]; then
        dir="$(readlink "/proc/${pid}/cwd" 2>/dev/null || echo '')"
        if [ -n "$dir" ] && [ -f "$dir/server.properties" ]; then
            echo "$dir"; return
        fi
    fi
    # Fallback: common locations
    rh="$(sudo -H -u "$RUN_USER" python3 -c 'import os;print(os.path.expanduser("~"))' 2>/dev/null || echo '')"
    for c in /data/minecraft_server "$rh/minecraft_server" "$rh/mc" /opt/minecraft_server; do
        if [ -f "$c/server.properties" ]; then
            echo "$c"; return
        fi
    done
    echo ""
}
MC_DIR="${MC_DIR:-}"
if [ -z "$MC_DIR" ]; then
    DETECT_MC_DIR="$(detect_mc_dir)"
    if [ -z "$DETECT_MC_DIR" ]; then
        echo "  No MC server directory detected, please enter it manually:"
        read -r -p "  MC server directory (contains server.jar / server.properties): " MC_DIR
        while [ -z "$MC_DIR" ]; do
            read -r -p "  MC server directory cannot be empty, please re-enter: " MC_DIR
        done
    else
        echo "  Detected MC server directory: [$DETECT_MC_DIR]"
        read -r -p "  Use this directory? (Y/n): " CONFIRM_MC_DIR
        if [[ "$CONFIRM_MC_DIR" =~ ^[Nn]$ ]]; then
            read -r -p "  Enter the MC server directory manually: " MC_DIR
            while [ -z "$MC_DIR" ]; do
                read -r -p "  MC server directory cannot be empty, please re-enter: " MC_DIR
            done
        else
            MC_DIR="$DETECT_MC_DIR"
        fi
    fi
fi
if [ ! -d "$MC_DIR" ]; then
    echo "  [WARN] MC directory $MC_DIR does not exist (the panel will still install, but plugin/log/backup features need it to work)"
fi

PANEL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUN_HOME="$(sudo -H -u "$RUN_USER" python3 -c 'import os; print(os.path.expanduser("~"))')"
GUNICORN_BIN="$RUN_HOME/.local/bin/gunicorn"

echo "============================================="
echo "  MCPanel - One-click Deployment"
echo "  Run user  : $RUN_USER"
echo "  Panel dir : $PANEL_DIR"
echo "  gunicorn  : $GUNICORN_BIN"
echo "  MC service: $MC_SERVICE_NAME (systemd/screen/tmux session name)"
echo "============================================="

# ---------- 1. System dependencies ----------
echo "[1/10] Updating package lists and installing system dependencies..."
apt-get update -y
apt-get install -y \
    python3 python3-pip python3-dev python3-venv \
    build-essential libssl-dev libffi-dev \
    xvfb x11vnc \
    curl wget git openssl

# ---------- 2a. Python virtual environment choice ----------
USE_VENV="${USE_VENV:-}"
if [ -z "$USE_VENV" ]; then
    echo "  Use a Python virtual environment? (Y/n, default: y): "
    read -r USE_VENV
    [ -z "$USE_VENV" ] && USE_VENV="y"
fi
if [[ "$USE_VENV" =~ ^[Yy]$ ]] && [ -d "$PANEL_DIR/venv" ]; then
    echo "  >> Existing virtual environment detected: $PANEL_DIR/venv (will be reused, not overwritten)"
fi

# ---------- 2. Python dependencies ----------
echo "[2/10] Installing Python dependencies..."
if [[ "$USE_VENV" =~ ^[Yy]$ ]]; then
    echo "  >> Creating virtual environment: $PANEL_DIR/venv"
    sudo -H -u "$RUN_USER" python3 -m venv "$PANEL_DIR/venv"
    sudo -H -u "$RUN_USER" "$PANEL_DIR/venv/bin/pip" install --upgrade pip
    sudo -H -u "$RUN_USER" "$PANEL_DIR/venv/bin/pip" install -r "$PANEL_DIR/requirements.txt"
    GUNICORN_BIN="$PANEL_DIR/venv/bin/gunicorn"
else
    echo "  >> Installing with --user (no virtual environment)"
    sudo -H -u "$RUN_USER" python3 -m pip install --upgrade pip
    sudo -H -u "$RUN_USER" python3 -m pip install --user -r "$PANEL_DIR/requirements.txt"
    GUNICORN_BIN="$RUN_HOME/.local/bin/gunicorn"
fi
echo "  >> gunicorn: $GUNICORN_BIN"

# ---------- 3. Directory layout ----------
echo "[3/10] Creating directory layout..."
mkdir -p "$PANEL_DIR/certs" "$PANEL_DIR/data" "$PANEL_DIR/static/avatars"
mkdir -p /data/mc_panel_logs
chown -R "$RUN_USER":"$RUN_USER" "$PANEL_DIR"

# ---------- 4. Panel protocol (HTTPS default, HTTP optional) ----------
PANEL_PROTO="${PANEL_PROTO:-}"
if [ -z "$PANEL_PROTO" ]; then
    echo "[4/10] Panel access protocol? [https/http] (default: https): "
    read -r PANEL_PROTO
    [ -z "$PANEL_PROTO" ] && PANEL_PROTO="https"
fi
case "$PANEL_PROTO" in
    http)
        echo "  >> WARNING: HTTP is NOT encrypted - passwords and traffic travel in plaintext."
        echo "     HTTPS is strongly recommended. Continuing with HTTP as you chose."
        ;;
    *)
        PANEL_PROTO="https"
        echo "[4/10] Checking HTTPS certificate..."
        if [ ! -f "$PANEL_DIR/certs/cert.pem" ] || [ ! -f "$PANEL_DIR/certs/key.pem" ]; then
            openssl req -x509 -newkey rsa:4096 -nodes \
                -out "$PANEL_DIR/certs/cert.pem" \
                -keyout "$PANEL_DIR/certs/key.pem" \
                -days 365 -subj "/CN=panel"
        fi
        chown -R "$RUN_USER":"$RUN_USER" "$PANEL_DIR/certs"
        ;;
esac

# ---------- 5. RCON password ----------
echo "[5/10] Configuring RCON password (MCRCON_PASS)..."
if [ -z "$MCRCON_PASS" ]; then
    read -r -s -p "Enter the MC server RCON password: " MCRCON_PASS
    echo
    if [ -z "$MCRCON_PASS" ]; then
        echo "Error: no RCON password provided. Use: MCRCON_PASS=xxx sudo bash preinstall.sh"
        exit 1
    fi
fi

# ---------- 6. frp reverse proxy prompt ----------
echo "[6/10] Asking about frp reverse proxy..."
FRP_MODE="none"
read -r -p "Use frp reverse proxy for the panel? (y/N): " USE_FRP
if [[ "$USE_FRP" =~ ^[Yy]$ ]]; then
    read -r -p "Does frp use (or plan to use) PROXY protocol V2 IP passthrough? (y/N): " FRP_V2
    if [[ "$FRP_V2" =~ ^[Yy]$ ]]; then
        FRP_MODE="v2"
        echo "  >> V2 passthrough enabled: panel listens on 127.0.0.1:8080, needs mmproxy in front (see note below)"
    else
        FRP_MODE="v1"
        echo "  >> frp forwards PROXY v1 text header, panel listens on 0.0.0.0:8080"
    fi
else
    echo "  >> No frp; panel listens directly on 0.0.0.0:8080"
fi

# ---------- 7. Backup dir + SECRET_KEY + env vars (merged into main unit) ----------
echo "[7/10] Configuring backup dir, generating SECRET_KEY and env vars (merged into main unit)..."
read -r -p "Set a separate backup dir (empty = default ${MC_DIR}/backups): " BACKUP_ROOT_INPUT
if [ -n "$BACKUP_ROOT_INPUT" ]; then
    ENV_BACKUP_ROOT="Environment=\"MC_BACKUP_ROOT=${BACKUP_ROOT_INPUT}\""
    echo "  >> Backup dir: $BACKUP_ROOT_INPUT"
    mkdir -p "$BACKUP_ROOT_INPUT/plugins_bak" "$BACKUP_ROOT_INPUT/server_jar_bak"
    chown -R "$RUN_USER":"$RUN_USER" "$BACKUP_ROOT_INPUT"
    echo "  >> Created plugins_bak / server_jar_bak subdirs"
else
    ENV_BACKUP_ROOT=""
    echo "  >> No separate backup dir (default will be used). Note: without a backup dir, backup/restore features may be unavailable"
    mkdir -p "$MC_DIR/backups/plugins_bak" "$MC_DIR/backups/server_jar_bak"
    chown -R "$RUN_USER":"$RUN_USER" "$MC_DIR/backups"
    echo "  >> Auto-created default backup dir $MC_DIR/backups/{plugins_bak,server_jar_bak}"
fi
SECRET_KEY="$(sudo -H -u "$RUN_USER" python3 -c 'import secrets; print(secrets.token_hex(32))')"
mkdir -p /etc/systemd/system/mcpanel.service.d
ENV_LINES="Environment=\"SECRET_KEY=${SECRET_KEY}\""
ENV_LINES="${ENV_LINES}
Environment=\"MCRCON_PASS=${MCRCON_PASS}\""
ENV_LINES="${ENV_LINES}
Environment=\"MC_DIR=${MC_DIR}\""
ENV_LINES="${ENV_LINES}
Environment=\"MC_SERVICE_NAME=${MC_SERVICE_NAME}\""
ENV_LINES="${ENV_LINES}
Environment=\"MC_LAUNCH_TYPE=${MC_LAUNCH_TYPE}\""
[ -n "$ENV_BACKUP_ROOT" ] && ENV_LINES="${ENV_LINES}
${ENV_BACKUP_ROOT}"
ENV_LINES="${ENV_LINES}
Environment=\"MC_LOG_DIR=/data/mc_panel_logs\""
if [ -n "$MC_LAUNCH_CMD" ]; then
    ENV_LINES="${ENV_LINES}
Environment=\"MC_LAUNCH_CMD=${MC_LAUNCH_CMD}\""
fi
echo "  >> Env vars will be merged into the main unit mcpanel.service (see step 9)"

# ---------- 8. gunicorn config (by frp mode) + passwordless sudo ----------
echo "[8/10] Generating gunicorn config (frp mode: $FRP_MODE)..."
if [ -f "$PANEL_DIR/gunicorn_config.py" ]; then
    mv "$PANEL_DIR/gunicorn_config.py" "$PANEL_DIR/gunicorn_config.py.bak-$(date +%Y%m%d%H%M%S)"
fi
if [ "$FRP_MODE" = "v2" ]; then
    GUNI_BIND="127.0.0.1:8080"
else
    GUNI_BIND="0.0.0.0:8080"
fi
cat > "$PANEL_DIR/gunicorn_config.py" <<EOF
# MCPanel gunicorn config (generated by preinstall.sh per frp mode)
bind = "$GUNI_BIND"
workers = 1
worker_class = "eventlet"
accesslog = "-"
EOF
if [ "$PANEL_PROTO" = "https" ]; then
cat >> "$PANEL_DIR/gunicorn_config.py" <<EOF
certfile = "certs/cert.pem"
keyfile = "certs/key.pem"
EOF
fi
if [ "$FRP_MODE" != "none" ]; then
cat >> "$PANEL_DIR/gunicorn_config.py" <<EOF
# PROXY protocol (pass real client IP to audit log)
proxy_protocol = True
proxy_allow_ips = ["127.0.0.1"]
EOF
fi
chown "$RUN_USER":"$RUN_USER" "$PANEL_DIR/gunicorn_config.py"
echo "  >> Generated $PANEL_DIR/gunicorn_config.py (bind=$GUNI_BIND, proxy=$FRP_MODE)"

if [ "$FRP_MODE" = "v2" ]; then
    echo
    echo "  !! [V2 passthrough] Deployment differs from the default:"
    echo "     gunicorn only parses the PROXY v1 text header; the V2 binary header needs mmproxy in front."
    echo "     1. Install mmproxy: github.com/cloudflare/mmproxy (make && cp mmproxy /usr/local/bin/)"
    echo "     2. mmproxy listens on 0.0.0.0:8081, forwards to panel 127.0.0.1:8080:"
    echo "        mmproxy -l 0.0.0.0:8081 -r 127.0.0.1:8080 -p 127.0.0.1:8080"
    echo "     3. In frpc.toml set transport.proxyProtocolVersion = \"v2\", remotePort points to 8081"
    echo "     4. The panel systemd unit stays unchanged (binds 127.0.0.1:8080, fed PROXY headers by mmproxy)"
    echo
fi

echo "[8/10] Configuring passwordless sudo..."
SUDOERS_FILE="/etc/sudoers.d/mcpanel-${RUN_USER}"
if [ "$MC_LAUNCH_TYPE" = "systemd" ]; then
    MC_SYSTEMCTL_LINE="${RUN_USER} ALL=(root) NOPASSWD: /usr/bin/systemctl start ${MC_SERVICE_NAME}, /usr/bin/systemctl stop ${MC_SERVICE_NAME}, /usr/bin/systemctl is-active ${MC_SERVICE_NAME}, /usr/bin/systemctl restart ${MC_SERVICE_NAME}"
else
    MC_SYSTEMCTL_LINE="# MC is managed by ${MC_LAUNCH_TYPE}, no systemctl passwordless entry"
fi
cat > "$SUDOERS_FILE" <<EOF
${MC_SYSTEMCTL_LINE}
${RUN_USER} ALL=(root) NOPASSWD: /usr/bin/lsattr
${RUN_USER} ALL=(root) NOPASSWD: /usr/bin/chattr +i ${MC_DIR%/}/ops.json, /usr/bin/chattr -i ${MC_DIR%/}/ops.json
${RUN_USER} ALL=(root) NOPASSWD: /usr/sbin/reboot, /sbin/reboot
EOF
chmod 440 "$SUDOERS_FILE"
visudo -c -f "$SUDOERS_FILE" && echo "  sudoers syntax OK: $SUDOERS_FILE"

# ---------- 9. systemd service ----------
echo "[9/10] Writing systemd service (mcpanel.service)..."
cat > /etc/systemd/system/mcpanel.service <<EOF
[Unit]
Description=MCPanel Minecraft Management Panel
After=network.target

[Service]
User=${RUN_USER}
Group=${RUN_USER}
WorkingDirectory=${PANEL_DIR}
${ENV_LINES}
ExecStart=${GUNICORN_BIN} -c gunicorn_config.py app:app
Restart=always
RestartSec=5
# MC server uses the front cores; panel is pinned to the last two (auto by core count, override with PANEL_CPU_AFFINITY)
CPUAffinity=${CPU_AFFINITY}

[Install]
WantedBy=multi-user.target
EOF

# ---------- 10. Start service ----------
echo "[10/10] Starting service..."
systemctl daemon-reload
systemctl enable mcpanel.service
systemctl restart mcpanel.service
sleep 3
systemctl status mcpanel.service --no-pager | head -10

PROTO_URL="https"
[ "$PANEL_PROTO" = "http" ] && PROTO_URL="http"

case "$FRP_MODE" in
    none) ACCESS_NOTE="$PROTO_URL://<SERVER_IP>:8080 direct access" ;;
    v1)   ACCESS_NOTE="frp mapped -> panel 8080 (PROXY v1, real IP passthrough)" ;;
    v2)   ACCESS_NOTE="frp + mmproxy -> panel 127.0.0.1:8080 (PROXY v2)" ;;
esac

echo
echo "============================================="
echo " Deployment complete!"
echo "  Access     : $ACCESS_NOTE"
echo "  Logs       : journalctl -u mcpanel.service -f"
echo "  Env vars   : SECRET_KEY / MCRCON_PASS / MC_DIR / MC_LOG_DIR merged into mcpanel.service main unit"
[ -n "$ENV_BACKUP_ROOT" ] && echo "  Backup dir : separate dir set (see MC_BACKUP_ROOT)"
echo "  Sudo       : /etc/sudoers.d/mcpanel-${RUN_USER} (systemctl ${MC_SERVICE_NAME} / chattr / reboot)"
echo "  MC manage  : ${MC_LAUNCH_TYPE} / ${MC_SERVICE_NAME}"
[ -n "$MC_LAUNCH_CMD" ] && echo "  MC launch  : ${MC_LAUNCH_CMD}"
echo "============================================="
